---
- hosts: localhost
  vars:
    cluster_name: 'Asia-Cluster1'
    datastore_name: 'ds_200'
    folder_name: 'prod'
    src_vm_name: Fedora34
    dest_vm_name: webserver
  tasks:
    - name: Get source virtual machine info
      vmware.vmware_rest.vcenter_vm_info:
        filter_names:
        - '{{ src_vm_name }}'
      register: vm_info

    - debug:
        msg: '{{ vm_info.value[0].vm }}'

    - name: Get Cluster info
      vmware.vmware_rest.vcenter_cluster_info:
        filter_names:
        - '{{ cluster_name }}'
      register: cluster_info

    - name: Get Resource info for {{ cluster_name }}
      vmware.vmware_rest.vcenter_cluster_info:
        cluster: '{{ cluster_info.value[0].cluster }}'
      register: resource_pool_info

    - name: Get datastore info
      vmware.vmware_rest.vcenter_datastore_info:
        filter_names:
        - '{{ datastore_name }}'
      register: datastore_info

    - name: Get folder info
      vmware.vmware_rest.vcenter_folder_info:
        filter_names:
        - '{{ folder_name }}'
      register: folder_info

    - set_fact:
        source_vm_id: '{{ vm_info.value[0].vm }}'
        datastore_id: '{{ datastore_info.value[0].datastore }}'
        folder_id: '{{ folder_info.value[0].folder }}'
        resource_pool_id: '{{ resource_pool_info.value.resource_pool }}'

    - name: Create a VM using clone
      vmware.vmware_rest.vcenter_vm:
        placement:
          datastore: '{{ datastore_id }}'
          folder: '{{ folder_id }}'
          resource_pool: '{{ resource_pool_id }}'
        name: '{{ dest_vm_name }}'
        source: '{{ source_vm_id }}'
        state: clone
      register: new_vm_info

    - debug:
        msg: "{{ new_vm_info }}"
